name: atu_alumni_app
description: "ATU Alumni Connect - Stay connected with your alma mater and fellow graduates."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/atu_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/atu_logo.png
